#name: Daily Newsletter
#
#on:
#  schedule:
#    - cron: '30 2 * * *'
#  workflow_dispatch:
#
#jobs:
#  send-newsletter:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout Repository
#      uses: actions/checkout@v3
#
#    - name: Python Set up
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.10'
#
#    - name: Install Dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - name: Run Newsletter
#      env:
#        EMAIL_USER: ${{ secrets.EMAIL_USER }}
#        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
#        DB_URL: ${{ secrets.DB_URL }}
#      run: |
#        python subscription.py

name: Daily Newsletter

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Newsletter
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          python subscription.py

